services:
    ai-text-game:
        image: ai-text-game:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app